language: java

jdk: oraclejdk8

services:
  - docker

dist: trusty

install:
  - mvn clean install -DskipTests

script:
  - docker-compose build
#  - docker-compose build
#  - docker tag shubhamarora97/travis-demo shubhamarora97/travis-demo:1.0
#  - docker push shubhamarora97/travis-demo:1.0
#  - docker pull shubhamarora97/travis-demo:1.0

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: Heroku
  api_key:
    secure: 4a378af3-5aca-4765-a4e2-969d3059685e
  app: demo-app-97
  skip_cleanup: true

