language: java

jdk: oraclejdk8

dist: trusty
install:
  - mvn clean install -DskipTests

script:
  - mvn test

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: Heroku
  api_key:
    secure: 4a378af3-5aca-4765-a4e2-969d3059685e
  app: demo-app-97